apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-generator
spec:
  schedule: '1 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-generator
              image: thomastoumasu/k8s-todo-generator:2.9
              env:
                - name: URL
                  value: 'http://backend-svc:2345/api/todos'
          restartPolicy: Never # run it only once
