apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
        - name: the-project
          image: thomastoumasu/k8s-the_project:1.5
          env:
            - name: PORT
              value: '5000'
