apiVersion: v1
kind: Service
metadata:
  name: the-project-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: the-project # app as declared in the deployment
  ports:
    - name: http
      nodePort: 30080 # port that is available outside. Value for nodePort can be between 30000-32767
      protocol: TCP
      port: 1234 # This is a port that is available to the cluster, in this case it can be ~ anything
      targetPort: 5000 # check env in deployment.yaml
