apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: restart-rate
spec:
  metrics:
    - name: restart-rate
      initialDelay: 2m
      successCondition: result < 2
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1766-prometheus.prometheus.svc.cluster.local:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
          query: |
            scalar(
              sum(kube_pod_container_status_restarts_total{namespace="exercises", container="pingpong"}) -
              sum(kube_pod_container_status_restarts_total{namespace="exercises", container="pingpong"} offset 2m)
            )
