apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports: # will let TCP traffic from port 1234 to port 3002
    - port: 1234
      protocol: TCP
      targetPort: 3002
