apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello
spec:
  parentRefs:
    - name: hello-gateway
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      backendRefs:
        - name: hello-svc-v1
          port: 80
          weight: 75
        - name: hello-svc-v2
          port: 80
          weight: 25
