apiVersion: v1
kind: Service
metadata:
  name: greeter-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: greeter
  ports: # will let TCP traffic from port 3456 to port 3004
    - port: 3456
      protocol: TCP
      targetPort: 3004 #check PORT env in deployment in same folder
