apiVersion: v1
kind: Pod
metadata:
  name: alpine-curl
  labels:
    app: alpine-curl
spec:
  containers:
    - image: alpine/curl
      command:
        - sleep
        - '3600'
      imagePullPolicy: IfNotPresent
      name: alpine-curl
  restartPolicy: Always
