apiVersion: v1
kind: Service
metadata:
  name: apps-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: apps
  ports: # will let TCP traffic from port 2345 to port 3000
    - port: 2345
      protocol: TCP
      targetPort: 3000
      name: log-output
    - port: 1234
      protocol: TCP
      targetPort: 3002
      name: pingpong
