# Health check configuration for the load balancer. For more information
# about these fields, see https://cloud.google.com/compute/docs/reference/rest/v1/healthChecks.
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: lb-healthcheck-frontend
  namespace: project
spec:
  default:
    checkIntervalSec: 30 # The default value is 15 seconds.
    timeoutSec: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 80
        requestPath: /
  # Attach to a Service in the cluster.
  targetRef:
    group: ''
    kind: Service
    name: frontend-svc
