apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  # - manifests/nodeport.yaml # if k3s
  - manifests/lb.yaml # if gke
images:
  - name: PROJECT/IMAGE # set by github actions for deployment on gke
    # newName: thomastoumasu/k8s-colorcontent:arm # if k3s without github actions
