apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: thomastoumasu/k8s-backend:3.3-amd
          env:
            - name: BACKEND_PORT
              value: '5000'
            - name: MONGODB_URI
              value: 'mongodb://the_username:the_password@mongo-svc.project:27017/the_database'
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: project
spec:
  type: NodePort # for ingress in gke
  selector:
    app: backend
  ports: # will let TCP traffic from port 2345 to port 5000
    - port: 2345
      protocol: TCP
      targetPort: 5000 #check env in deployment above
