apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # image: thomastoumasu/k8s-backend:3.3-amd
          image: PROJECT/BACKEND_IMAGE # see kustomization.yaml in the root folder
          env:
            - name: BACKEND_PORT
              value: '5000'
            - name: MONGODB_URI
              value: 'mongodb://the_username:the_password@mongo-svc:27017/the_database'
            - name: NATS_URL
              value: nats://my-nats:4222
          resources:
            requests: # kube-scheduler uses this information to decide which node to place the Pod on and reserves at least this amount specifically for that container to use
                memory: "64Mi" # in bytes, i for power of 2
                cpu: "100m" # 1 CPU unit is equivalent to 1 physical CPU core, or 1 virtual core, depending on whether the node is a physical host or a virtual machine running inside a physical machine.
            limits: # kubelet enforces the limit so that the running container is not allowed to use more of that resource:
              memory: "128Mi" # Above this, the kernel may terminate the container (OOMKilled, Out Of Memory) when it detects memory pressure. 
              cpu: "500m" # Around this, the kernel will restrict access to the CPU (CPU throttling).
          readinessProbe:
            initialDelaySeconds: 30 # Initial delay until the readiness is tested
            periodSeconds: 15 # How often to test
            httpGet:
              path: /health
              port: 5000
          livenessProbe:
            initialDelaySeconds: 60 # Initial delay until the liveness is tested
            periodSeconds: 15 # How often to test
            httpGet:
              path: /health
              port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: project
spec:
  type: ClusterIP # for gateway in gke
  selector:
    app: backend
  ports: # will let TCP traffic from port 2345 to port 5000
    - port: 2345
      protocol: TCP
      targetPort: 5000 #check env in deployment above
