apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: project
spec:
  parentRefs:
    - name: my-gateway
  hostnames:
    - www.thomastoumasu.xx.kg
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/todos
      backendRefs:
        - name: backend-svc
          port: 2345
