name: Backup db
on:
  push:
  # schedule:
  # - cron: "* * * * *"

env:
  BUCKET: thomastoumasu_k8s-bucket
  MONGO_URI: mongodb://the_username:the_password@mongo-svc.project:27017/the_database
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: my-repository
  DUMPER_IMAGE: dumper
  BRANCH: main

jobs:
  backup-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: 'Set up Docker Buildx'
        run: gcloud auth configure-docker "$REGISTRY"

      - name: 'Form the image name'
        run: echo "DUMPER_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$DUMPER_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build
        run: docker build --platform linux/amd64 --tag $DUMPER_IMAGE_TAG ./the_project/mongo/dumper

      - name: Publish
        run: docker push $DUMPER_IMAGE_TAG

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy dumper pod
        run: |
          echo '${{ secrets.GKE_SA_KEY }}' > ./private-key.json
          kubectl run dumper -v "./private.key.json:/usr/src/app/private-key.json" --image=$DUMPER_IMAGE_TAG

      # - name: 'Setup mongodb-tools'
      #   run: |
      #     wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.6.1.deb
      #     sudo apt install ./mongodb-database-tools-*-100.6.1.deb
      #     mongorestore --version

      # - name: Create test file
      #   run: >-
      #     echo \
      #     '[
      #       {
      #         "name": "delete-branch-images",
      #         "action": { "type": "Delete" },
      #         "condition": {
      #           "tagState": "tagged",
      #           "tagPrefixes": ["yeah"]
      #         }
      #       }
      #     ]'
      #     > delete-policy.json

      # - name: Send File to Google Global Storage
      #   run: gcloud storage cp delete-policy.json gs://${BUCKET}

      # - name: 'Dump the mongo db'
      #   run: mongodump --uri=$MONGO_URI --out $(pwd)

      # - name: 'Set filename to be used for the dump in Google GLobal Storage'
      #   # run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      #   run: |
      #     NOW=$(date +'%Y-%m-%dT%H-%M-%S')
      #     echo "FILENAME="./the_database/todos-${NOW}.bson"" >> $GITHUB_ENV

      # - name: 'Rename dump'
      #   run: mv ./the_database/todos.bson $FILENAME

      # - name: 'Send dump to Google Global Storage'
      #   run: gcloud storage cp $FILENAME gs://${BUCKET}
