name: Release application
# first create cluster as dwk-cluster, for example with sh create_gkecl_big_gat.sh
# gateway IP must be known and built into ENV VITE_BACKEND_URL in frontend Dockerfile

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: my-repository
  BACKEND_IMAGE: backend
  FRONTEND_IMAGE: frontend
  IMAGEFINDER_IMAGE: image-finder
  DB_IMAGE: mongo
  SERVICE: backend-dep
  BRANCH: ${{ github.ref_name }}
  BRANCH2: ${GITHUB_REF#refs/heads/}
  BRANCH3: ${{ github.head_ref || github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Set up Docker Buildx'
        run: gcloud auth configure-docker "$REGISTRY"

      - name: 'Form the images names'
        run: |-
          echo "BACKEND_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$BACKEND_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$FRONTEND_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "IMAGEFINDER_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGEFINDER_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "DB_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$DB_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      # - name: Build
      #   run: |-
      #     docker build --platform linux/amd64 --tag $BACKEND_IMAGE_TAG ./the_project/backend
      #     docker build --platform linux/amd64 --tag $FRONTEND_IMAGE_TAG ./the_project/frontend
      #     docker build --platform linux/amd64 --tag $IMAGEFINDER_IMAGE_TAG ./the_project/image-finder
      #     docker build --platform linux/amd64 --tag $DB_IMAGE_TAG ./the_project/mongo

      # - name: Publish
      #   run: |-
      #     docker push $BACKEND_IMAGE_TAG
      #     docker push $FRONTEND_IMAGE_TAG
      #     docker push $IMAGEFINDER_IMAGE_TAG
      #     docker push $DB_IMAGE_TAG

      # - name: Set up Kustomize
      #   uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy
        run: |-
          echo "BRANCH=$BRANCH"
          echo "BRANCH2=$BRANCH2"
          echo "BRANCH3=$BRANCH3"
          case $BRANCH3 in
            main)
              echo "NAMESPACE="project"" >> $GITHUB_ENV
              ;;
            *)
              echo "NAMESPACE=$BRANCH3" >> $GITHUB_ENV
              ;;
          esac

          kubectl create namespace $NAMESPACE || true
          kubectl config set-context --current --namespace=$NAMESPACE
          cd ./the_project
          kustomize edit set namespace $NAMESPACE
          kustomize edit set image PROJECT/BACKEND_IMAGE=$BACKEND_IMAGE_TAG
          kustomize edit set image PROJECT/FRONTEND_IMAGE=$FRONTEND_IMAGE_TAG
          kustomize edit set image PROJECT/IMAGEFINDER_IMAGE=$IMAGEFINDER_IMAGE_TAG
          kustomize edit set image PROJECT/DB_IMAGE=$DB_IMAGE_TAG
          kustomize build . | cat
          # kustomize build . | kubectl apply -f -
          # kubectl get all -n project
          # kubectl get events -n project  --sort-by='.lastTimestamp'
          # kubectl rollout status deployment $SERVICE
          # kubectl get services -o wide
          # kubectl get gateway my-gateway
