name: Build and publish application
# creates application images, store them in image repo, patches the kustomization.yaml with the image names and checks it in.
# Contrary to push-deploy_the-project.yaml, do not deploy, so no need to open access to cluster to this action (so no cluster credentials given).
# Deployment will be taken care of by ArgoCD, that watches changes to the kustomization.yaml.
# check ex4_8.sh to set up ArgoCD.
# Needed: a service account .json file as GKE_SA_KEY (= put full file in repo environment secret): gcloud iam service-accounts keys create ./private-key.json --iam-account=github-actions@dwk-gke-331210.iam.gserviceaccount.com
# Note: cluster gateway IP must be known and built into ENV VITE_BACKEND_URL in frontend Dockerfile so that frontend can reach backend from browser.
# here this is done with a domain name so only need to put the gateway IP in the cloudflare DNS record for the domains (see SITE below).

on:
  push:
    branches:
      - main
  release:
    types: [published]

env:
  # contains the branch name (so main) on push without tag (e.g. normal commit) or the tag on push with tag (e.g. release)
  EVENT: ${{ github.ref_name }}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: my-repository
  BACKEND_IMAGE: backend
  FRONTEND_IMAGE: frontend
  IMAGEFINDER_IMAGE: image-finder
  DB_IMAGE: mongo
  BROADCASTER_IMAGE: broadcaster
  WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  SERVICE: backend-dep

jobs:
  set-environment:
    name: Sets environment
    runs-on: ubuntu-latest
    outputs:
      namespace: ${{ steps.set.outputs.NAMESPACE }}
      site: ${{ steps.set.outputs.SITE }}
    steps:
      - name: Set namespace and domain name depending on github event
        id: set
        run: |
          echo "event is $EVENT - if main, commit has no tag so staging, if something else, then commit is tagged so production"
          case $EVENT in
            main) 
              echo "NAMESPACE="staging"" >> $GITHUB_OUTPUT
              echo "SITE="www.thomastoumasu.xx.kg"" >> $GITHUB_OUTPUT
              ;;
            *) 
              echo "NAMESPACE="production"" >> $GITHUB_OUTPUT
              echo "SITE="www.thomastoumasu.dpdns.org"" >> $GITHUB_OUTPUT
              ;;
          esac

  build-release-patch:
    name: Builds images and checks in patched configuration
    needs: [set-environment]
    runs-on: ubuntu-latest
    env:
      NAMESPACE: ${{ needs.set-environment.outputs.namespace }}
      SITE: ${{ needs.set-environment.outputs.site }}
    outputs:
      kustomization: ${{ steps.define-file.outputs.KUSTOMIZATION_FILE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main' # necessary in the release case -- Supposes releases are only created on main.

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: 'Set up Docker Buildx'
        run: gcloud auth configure-docker "$REGISTRY"

      - name: 'Form the images names'
        run: |-
          echo "BACKEND_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$BACKEND_IMAGE:$NAMESPACE-$GITHUB_SHA" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$FRONTEND_IMAGE:$NAMESPACE-$GITHUB_SHA" >> $GITHUB_ENV
          echo "IMAGEFINDER_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGEFINDER_IMAGE:$NAMESPACE-$GITHUB_SHA" >> $GITHUB_ENV
          echo "DB_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$DB_IMAGE:$NAMESPACE-$GITHUB_SHA" >> $GITHUB_ENV
          echo "BROADCASTER_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$BROADCASTER_IMAGE:$NAMESPACE-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build
        run: |-
          docker build --build-arg ENVIRONMENT=$NAMESPACE --platform linux/amd64 --tag $BACKEND_IMAGE_TAG ./the_project/backend
          docker build --build-arg VITE_BACKEND_URL="http://${SITE}/api/todos" --platform linux/amd64 --tag $FRONTEND_IMAGE_TAG ./the_project/frontend
          docker build --platform linux/amd64 --tag $IMAGEFINDER_IMAGE_TAG ./the_project/image-finder
          docker build --platform linux/amd64 --tag $DB_IMAGE_TAG ./the_project/mongo
          docker build --build-arg DISCORD_WEBHOOK=$WEBHOOK --platform linux/amd64 --tag $BROADCASTER_IMAGE_TAG ./the_project/broadcaster

      - name: Publish to images repo
        run: |-
          docker push $BACKEND_IMAGE_TAG
          docker push $FRONTEND_IMAGE_TAG
          docker push $IMAGEFINDER_IMAGE_TAG
          docker push $DB_IMAGE_TAG
          docker push $BROADCASTER_IMAGE_TAG

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Defines the right kustomization path and file
        id: define-file
        run: |-
          echo "KUSTOMIZATION_PATH="./the_project/kustomize/overlays/${NAMESPACE}"" >> $GITHUB_ENV
          echo "KUSTOMIZATION_FILE="./the_project/kustomize/overlays/${NAMESPACE}/kustomization.yaml"" >> $GITHUB_ENV

      - name: Patch image names into the kustomization.yaml corresponding to the github event
        run: |-
          cd $KUSTOMIZATION_PATH
          kustomize edit set image PROJECT/BACKEND_IMAGE=$BACKEND_IMAGE_TAG
          kustomize edit set image PROJECT/FRONTEND_IMAGE=$FRONTEND_IMAGE_TAG
          kustomize edit set image PROJECT/IMAGEFINDER_IMAGE=$IMAGEFINDER_IMAGE_TAG
          kustomize edit set image PROJECT/DB_IMAGE=$DB_IMAGE_TAG
          kustomize edit set image PROJECT/BROADCASTER_IMAGE=$BROADCASTER_IMAGE_TAG
          echo "Configuration about to be checked in: "
          kustomize build . | cat

      - name: Commit patched kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: './the_project/kustomize/overlays/'
          message: New version released ${{ github.sha }}
