name: test

on:
  push:

env:
  NAMESPACE: newtest-sharedgta

jobs:
  create-delete-policy:
    name: Create delete policy
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        run: >-
          echo \
          '[
            {
              "name": "delete-branch-images",
              "action": { "type": "Delete" },
              "condition": {
                "tagState": "tagged",
                "tagPrefixes": ['$NAMESPACE']
              }
            }
          ]'
          > delete.json

      - name: Print file
        run: cat delete.json
